/*
 * FutDB
 * The Fifa Ultimate Team Database API is a JSON REST API.<br> We offer a complete, easy to understand JSON REST API with a complete database of players, prices, nations, leagues, clubs, and card-types.<br> Please note that some data fields are only delivered with a premium account.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * GetPlayerPriceResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-24T14:15:34.912+02:00")
public class GetPlayerPriceResponse {
  @SerializedName("playstation")
  private Price playstation = null;

  @SerializedName("xbox")
  private Price xbox = null;

  @SerializedName("pc")
  private Price pc = null;

  public GetPlayerPriceResponse playstation(Price playstation) {
    this.playstation = playstation;
    return this;
  }

   /**
   * Get playstation
   * @return playstation
  **/

  public Price getPlaystation() {
    return playstation;
  }

  public void setPlaystation(Price playstation) {
    this.playstation = playstation;
  }

  public GetPlayerPriceResponse xbox(Price xbox) {
    this.xbox = xbox;
    return this;
  }

   /**
   * Get xbox
   * @return xbox
  **/

  public Price getXbox() {
    return xbox;
  }

  public void setXbox(Price xbox) {
    this.xbox = xbox;
  }

  public GetPlayerPriceResponse pc(Price pc) {
    this.pc = pc;
    return this;
  }

   /**
   * Get pc
   * @return pc
  **/

  public Price getPc() {
    return pc;
  }

  public void setPc(Price pc) {
    this.pc = pc;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPlayerPriceResponse getPlayerPriceResponse = (GetPlayerPriceResponse) o;
    return Objects.equals(this.playstation, getPlayerPriceResponse.playstation) &&
        Objects.equals(this.xbox, getPlayerPriceResponse.xbox) &&
        Objects.equals(this.pc, getPlayerPriceResponse.pc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(playstation, xbox, pc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPlayerPriceResponse {\n");
    
    sb.append("    playstation: ").append(toIndentedString(playstation)).append("\n");
    sb.append("    xbox: ").append(toIndentedString(xbox)).append("\n");
    sb.append("    pc: ").append(toIndentedString(pc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

