/*
 * FutDB
 * The Fifa Ultimate Team Database API is a JSON REST API.<br> We offer a complete, easy to understand JSON REST API with a complete database of players, prices, nations, leagues, clubs, and card-types.<br> Please note that some data fields are only delivered with a premium account.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * PlayerPace
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-24T14:15:34.912+02:00")
public class PlayerPace {
  @SerializedName("acceleration")
  private Integer acceleration = null;

  @SerializedName("sprint_speed")
  private Integer sprintSpeed = null;

  public PlayerPace acceleration(Integer acceleration) {
    this.acceleration = acceleration;
    return this;
  }

   /**
   * Get acceleration
   * @return acceleration
  **/

  public Integer getAcceleration() {
    return acceleration;
  }

  public void setAcceleration(Integer acceleration) {
    this.acceleration = acceleration;
  }

  public PlayerPace sprintSpeed(Integer sprintSpeed) {
    this.sprintSpeed = sprintSpeed;
    return this;
  }

   /**
   * Get sprintSpeed
   * @return sprintSpeed
  **/

  public Integer getSprintSpeed() {
    return sprintSpeed;
  }

  public void setSprintSpeed(Integer sprintSpeed) {
    this.sprintSpeed = sprintSpeed;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerPace playerPace = (PlayerPace) o;
    return Objects.equals(this.acceleration, playerPace.acceleration) &&
        Objects.equals(this.sprintSpeed, playerPace.sprintSpeed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acceleration, sprintSpeed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerPace {\n");
    
    sb.append("    acceleration: ").append(toIndentedString(acceleration)).append("\n");
    sb.append("    sprintSpeed: ").append(toIndentedString(sprintSpeed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

