/*
 * FutDB
 * The Fifa Ultimate Team Database API is a JSON REST API.<br> We offer a complete, easy to understand JSON REST API with a complete database of players, prices, nations, leagues, clubs, and card-types.<br> Please note that some data fields are only delivered with a premium account.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;
import org.joda.time.DateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Player
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-24T14:15:34.912+02:00")
public class Player {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("resource_id")
  private Integer resourceId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("age")
  private Integer age = null;

  @SerializedName("resource_base_id")
  private Integer resourceBaseId = null;

  @SerializedName("fut_bin_id")
  private Integer futBinId = null;

  @SerializedName("fut_wiz_id")
  private Integer futWizId = null;

  @SerializedName("first_name")
  private String firstName = null;

  @SerializedName("last_name")
  private String lastName = null;

  @SerializedName("common_name")
  private String commonName = null;

  @SerializedName("height")
  private Integer height = null;

  @SerializedName("weight")
  private Integer weight = null;

  @SerializedName("birth_date")
  private DateTime birthDate = null;

  @SerializedName("league")
  private Integer league = null;

  @SerializedName("nation")
  private Integer nation = null;

  @SerializedName("club")
  private Integer club = null;

  @SerializedName("rarity")
  private Integer rarity = null;

  @SerializedName("traits")
  private List<SimpleName> traits = null;

  @SerializedName("specialities")
  private List<SimpleName> specialities = null;

  @SerializedName("tradeable")
  private Boolean tradeable = null;

  @SerializedName("position")
  private String position = null;

  @SerializedName("skill_moves")
  private Integer skillMoves = null;

  @SerializedName("weak_foot")
  private Integer weakFoot = null;

  @SerializedName("foot")
  private String foot = null;

  @SerializedName("attack_work_rate")
  private String attackWorkRate = null;

  @SerializedName("defense_work_rate")
  private String defenseWorkRate = null;

  @SerializedName("total_stats")
  private Integer totalStats = null;

  @SerializedName("total_stats_in_game")
  private Integer totalStatsInGame = null;

  @SerializedName("rating")
  private Integer rating = null;

  @SerializedName("rating_average")
  private Integer ratingAverage = null;

  @SerializedName("pace")
  private Integer pace = null;

  @SerializedName("shooting")
  private Integer shooting = null;

  @SerializedName("passing")
  private Integer passing = null;

  @SerializedName("dribbling")
  private Integer dribbling = null;

  @SerializedName("defending")
  private Integer defending = null;

  @SerializedName("physicality")
  private Integer physicality = null;

  @SerializedName("pace_attributes")
  private PlayerPace paceAttributes = null;

  @SerializedName("shooting_attributes")
  private PlayerShooting shootingAttributes = null;

  @SerializedName("passing_attributes")
  private PlayerPassing passingAttributes = null;

  @SerializedName("dribbling_attributes")
  private PlayerDribbling dribblingAttributes = null;

  @SerializedName("defending_attributes")
  private PlayerDefending defendingAttributes = null;

  @SerializedName("physicality_attributes")
  private PlayerPhysicality physicalityAttributes = null;

  @SerializedName("goalkeeper_attributes")
  private PlayerGoalkeeper goalkeeperAttributes = null;

  public Player id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Player resourceId(Integer resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * Get resourceId
   * @return resourceId
  **/

  public Integer getResourceId() {
    return resourceId;
  }

  public void setResourceId(Integer resourceId) {
    this.resourceId = resourceId;
  }

  public Player name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Player age(Integer age) {
    this.age = age;
    return this;
  }

   /**
   * Get age
   * @return age
  **/

  public Integer getAge() {
    return age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }

  public Player resourceBaseId(Integer resourceBaseId) {
    this.resourceBaseId = resourceBaseId;
    return this;
  }

   /**
   * Get resourceBaseId
   * @return resourceBaseId
  **/

  public Integer getResourceBaseId() {
    return resourceBaseId;
  }

  public void setResourceBaseId(Integer resourceBaseId) {
    this.resourceBaseId = resourceBaseId;
  }

  public Player futBinId(Integer futBinId) {
    this.futBinId = futBinId;
    return this;
  }

   /**
   * Get futBinId
   * @return futBinId
  **/

  public Integer getFutBinId() {
    return futBinId;
  }

  public void setFutBinId(Integer futBinId) {
    this.futBinId = futBinId;
  }

  public Player futWizId(Integer futWizId) {
    this.futWizId = futWizId;
    return this;
  }

   /**
   * Get futWizId
   * @return futWizId
  **/

  public Integer getFutWizId() {
    return futWizId;
  }

  public void setFutWizId(Integer futWizId) {
    this.futWizId = futWizId;
  }

  public Player firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/

  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public Player lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/

  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public Player commonName(String commonName) {
    this.commonName = commonName;
    return this;
  }

   /**
   * Get commonName
   * @return commonName
  **/

  public String getCommonName() {
    return commonName;
  }

  public void setCommonName(String commonName) {
    this.commonName = commonName;
  }

  public Player height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/

  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public Player weight(Integer weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Get weight
   * @return weight
  **/

  public Integer getWeight() {
    return weight;
  }

  public void setWeight(Integer weight) {
    this.weight = weight;
  }

  public Player birthDate(DateTime birthDate) {
    this.birthDate = birthDate;
    return this;
  }

   /**
   * Get birthDate
   * @return birthDate
  **/

  public DateTime getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(DateTime birthDate) {
    this.birthDate = birthDate;
  }

  public Player league(Integer league) {
    this.league = league;
    return this;
  }

   /**
   * Get league
   * @return league
  **/

  public Integer getLeague() {
    return league;
  }

  public void setLeague(Integer league) {
    this.league = league;
  }

  public Player nation(Integer nation) {
    this.nation = nation;
    return this;
  }

   /**
   * Get nation
   * @return nation
  **/

  public Integer getNation() {
    return nation;
  }

  public void setNation(Integer nation) {
    this.nation = nation;
  }

  public Player club(Integer club) {
    this.club = club;
    return this;
  }

   /**
   * Get club
   * @return club
  **/

  public Integer getClub() {
    return club;
  }

  public void setClub(Integer club) {
    this.club = club;
  }

  public Player rarity(Integer rarity) {
    this.rarity = rarity;
    return this;
  }

   /**
   * Get rarity
   * @return rarity
  **/

  public Integer getRarity() {
    return rarity;
  }

  public void setRarity(Integer rarity) {
    this.rarity = rarity;
  }

  public Player traits(List<SimpleName> traits) {
    this.traits = traits;
    return this;
  }

  public Player addTraitsItem(SimpleName traitsItem) {
    if (this.traits == null) {
      this.traits = new ArrayList<SimpleName>();
    }
    this.traits.add(traitsItem);
    return this;
  }

   /**
   * Get traits
   * @return traits
  **/

  public List<SimpleName> getTraits() {
    return traits;
  }

  public void setTraits(List<SimpleName> traits) {
    this.traits = traits;
  }

  public Player specialities(List<SimpleName> specialities) {
    this.specialities = specialities;
    return this;
  }

  public Player addSpecialitiesItem(SimpleName specialitiesItem) {
    if (this.specialities == null) {
      this.specialities = new ArrayList<SimpleName>();
    }
    this.specialities.add(specialitiesItem);
    return this;
  }

   /**
   * Get specialities
   * @return specialities
  **/

  public List<SimpleName> getSpecialities() {
    return specialities;
  }

  public void setSpecialities(List<SimpleName> specialities) {
    this.specialities = specialities;
  }

  public Player tradeable(Boolean tradeable) {
    this.tradeable = tradeable;
    return this;
  }

   /**
   * Get tradeable
   * @return tradeable
  **/

  public Boolean getTradeable() {
    return tradeable;
  }

  public void setTradeable(Boolean tradeable) {
    this.tradeable = tradeable;
  }

  public Player position(String position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/

  public String getPosition() {
    return position;
  }

  public void setPosition(String position) {
    this.position = position;
  }

  public Player skillMoves(Integer skillMoves) {
    this.skillMoves = skillMoves;
    return this;
  }

   /**
   * Get skillMoves
   * @return skillMoves
  **/

  public Integer getSkillMoves() {
    return skillMoves;
  }

  public void setSkillMoves(Integer skillMoves) {
    this.skillMoves = skillMoves;
  }

  public Player weakFoot(Integer weakFoot) {
    this.weakFoot = weakFoot;
    return this;
  }

   /**
   * Get weakFoot
   * @return weakFoot
  **/

  public Integer getWeakFoot() {
    return weakFoot;
  }

  public void setWeakFoot(Integer weakFoot) {
    this.weakFoot = weakFoot;
  }

  public Player foot(String foot) {
    this.foot = foot;
    return this;
  }

   /**
   * Get foot
   * @return foot
  **/

  public String getFoot() {
    return foot;
  }

  public void setFoot(String foot) {
    this.foot = foot;
  }

  public Player attackWorkRate(String attackWorkRate) {
    this.attackWorkRate = attackWorkRate;
    return this;
  }

   /**
   * Get attackWorkRate
   * @return attackWorkRate
  **/

  public String getAttackWorkRate() {
    return attackWorkRate;
  }

  public void setAttackWorkRate(String attackWorkRate) {
    this.attackWorkRate = attackWorkRate;
  }

  public Player defenseWorkRate(String defenseWorkRate) {
    this.defenseWorkRate = defenseWorkRate;
    return this;
  }

   /**
   * Get defenseWorkRate
   * @return defenseWorkRate
  **/

  public String getDefenseWorkRate() {
    return defenseWorkRate;
  }

  public void setDefenseWorkRate(String defenseWorkRate) {
    this.defenseWorkRate = defenseWorkRate;
  }

  public Player totalStats(Integer totalStats) {
    this.totalStats = totalStats;
    return this;
  }

   /**
   * Get totalStats
   * @return totalStats
  **/

  public Integer getTotalStats() {
    return totalStats;
  }

  public void setTotalStats(Integer totalStats) {
    this.totalStats = totalStats;
  }

  public Player totalStatsInGame(Integer totalStatsInGame) {
    this.totalStatsInGame = totalStatsInGame;
    return this;
  }

   /**
   * Get totalStatsInGame
   * @return totalStatsInGame
  **/

  public Integer getTotalStatsInGame() {
    return totalStatsInGame;
  }

  public void setTotalStatsInGame(Integer totalStatsInGame) {
    this.totalStatsInGame = totalStatsInGame;
  }

  public Player rating(Integer rating) {
    this.rating = rating;
    return this;
  }

   /**
   * Get rating
   * @return rating
  **/

  public Integer getRating() {
    return rating;
  }

  public void setRating(Integer rating) {
    this.rating = rating;
  }

  public Player ratingAverage(Integer ratingAverage) {
    this.ratingAverage = ratingAverage;
    return this;
  }

   /**
   * Get ratingAverage
   * @return ratingAverage
  **/

  public Integer getRatingAverage() {
    return ratingAverage;
  }

  public void setRatingAverage(Integer ratingAverage) {
    this.ratingAverage = ratingAverage;
  }

  public Player pace(Integer pace) {
    this.pace = pace;
    return this;
  }

   /**
   * Get pace
   * @return pace
  **/

  public Integer getPace() {
    return pace;
  }

  public void setPace(Integer pace) {
    this.pace = pace;
  }

  public Player shooting(Integer shooting) {
    this.shooting = shooting;
    return this;
  }

   /**
   * Get shooting
   * @return shooting
  **/

  public Integer getShooting() {
    return shooting;
  }

  public void setShooting(Integer shooting) {
    this.shooting = shooting;
  }

  public Player passing(Integer passing) {
    this.passing = passing;
    return this;
  }

   /**
   * Get passing
   * @return passing
  **/

  public Integer getPassing() {
    return passing;
  }

  public void setPassing(Integer passing) {
    this.passing = passing;
  }

  public Player dribbling(Integer dribbling) {
    this.dribbling = dribbling;
    return this;
  }

   /**
   * Get dribbling
   * @return dribbling
  **/

  public Integer getDribbling() {
    return dribbling;
  }

  public void setDribbling(Integer dribbling) {
    this.dribbling = dribbling;
  }

  public Player defending(Integer defending) {
    this.defending = defending;
    return this;
  }

   /**
   * Get defending
   * @return defending
  **/

  public Integer getDefending() {
    return defending;
  }

  public void setDefending(Integer defending) {
    this.defending = defending;
  }

  public Player physicality(Integer physicality) {
    this.physicality = physicality;
    return this;
  }

   /**
   * Get physicality
   * @return physicality
  **/

  public Integer getPhysicality() {
    return physicality;
  }

  public void setPhysicality(Integer physicality) {
    this.physicality = physicality;
  }

  public Player paceAttributes(PlayerPace paceAttributes) {
    this.paceAttributes = paceAttributes;
    return this;
  }

   /**
   * Get paceAttributes
   * @return paceAttributes
  **/

  public PlayerPace getPaceAttributes() {
    return paceAttributes;
  }

  public void setPaceAttributes(PlayerPace paceAttributes) {
    this.paceAttributes = paceAttributes;
  }

  public Player shootingAttributes(PlayerShooting shootingAttributes) {
    this.shootingAttributes = shootingAttributes;
    return this;
  }

   /**
   * Get shootingAttributes
   * @return shootingAttributes
  **/

  public PlayerShooting getShootingAttributes() {
    return shootingAttributes;
  }

  public void setShootingAttributes(PlayerShooting shootingAttributes) {
    this.shootingAttributes = shootingAttributes;
  }

  public Player passingAttributes(PlayerPassing passingAttributes) {
    this.passingAttributes = passingAttributes;
    return this;
  }

   /**
   * Get passingAttributes
   * @return passingAttributes
  **/

  public PlayerPassing getPassingAttributes() {
    return passingAttributes;
  }

  public void setPassingAttributes(PlayerPassing passingAttributes) {
    this.passingAttributes = passingAttributes;
  }

  public Player dribblingAttributes(PlayerDribbling dribblingAttributes) {
    this.dribblingAttributes = dribblingAttributes;
    return this;
  }

   /**
   * Get dribblingAttributes
   * @return dribblingAttributes
  **/

  public PlayerDribbling getDribblingAttributes() {
    return dribblingAttributes;
  }

  public void setDribblingAttributes(PlayerDribbling dribblingAttributes) {
    this.dribblingAttributes = dribblingAttributes;
  }

  public Player defendingAttributes(PlayerDefending defendingAttributes) {
    this.defendingAttributes = defendingAttributes;
    return this;
  }

   /**
   * Get defendingAttributes
   * @return defendingAttributes
  **/

  public PlayerDefending getDefendingAttributes() {
    return defendingAttributes;
  }

  public void setDefendingAttributes(PlayerDefending defendingAttributes) {
    this.defendingAttributes = defendingAttributes;
  }

  public Player physicalityAttributes(PlayerPhysicality physicalityAttributes) {
    this.physicalityAttributes = physicalityAttributes;
    return this;
  }

   /**
   * Get physicalityAttributes
   * @return physicalityAttributes
  **/

  public PlayerPhysicality getPhysicalityAttributes() {
    return physicalityAttributes;
  }

  public void setPhysicalityAttributes(PlayerPhysicality physicalityAttributes) {
    this.physicalityAttributes = physicalityAttributes;
  }

  public Player goalkeeperAttributes(PlayerGoalkeeper goalkeeperAttributes) {
    this.goalkeeperAttributes = goalkeeperAttributes;
    return this;
  }

   /**
   * Get goalkeeperAttributes
   * @return goalkeeperAttributes
  **/

  public PlayerGoalkeeper getGoalkeeperAttributes() {
    return goalkeeperAttributes;
  }

  public void setGoalkeeperAttributes(PlayerGoalkeeper goalkeeperAttributes) {
    this.goalkeeperAttributes = goalkeeperAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Player player = (Player) o;
    return Objects.equals(this.id, player.id) &&
        Objects.equals(this.resourceId, player.resourceId) &&
        Objects.equals(this.name, player.name) &&
        Objects.equals(this.age, player.age) &&
        Objects.equals(this.resourceBaseId, player.resourceBaseId) &&
        Objects.equals(this.futBinId, player.futBinId) &&
        Objects.equals(this.futWizId, player.futWizId) &&
        Objects.equals(this.firstName, player.firstName) &&
        Objects.equals(this.lastName, player.lastName) &&
        Objects.equals(this.commonName, player.commonName) &&
        Objects.equals(this.height, player.height) &&
        Objects.equals(this.weight, player.weight) &&
        Objects.equals(this.birthDate, player.birthDate) &&
        Objects.equals(this.league, player.league) &&
        Objects.equals(this.nation, player.nation) &&
        Objects.equals(this.club, player.club) &&
        Objects.equals(this.rarity, player.rarity) &&
        Objects.equals(this.traits, player.traits) &&
        Objects.equals(this.specialities, player.specialities) &&
        Objects.equals(this.tradeable, player.tradeable) &&
        Objects.equals(this.position, player.position) &&
        Objects.equals(this.skillMoves, player.skillMoves) &&
        Objects.equals(this.weakFoot, player.weakFoot) &&
        Objects.equals(this.foot, player.foot) &&
        Objects.equals(this.attackWorkRate, player.attackWorkRate) &&
        Objects.equals(this.defenseWorkRate, player.defenseWorkRate) &&
        Objects.equals(this.totalStats, player.totalStats) &&
        Objects.equals(this.totalStatsInGame, player.totalStatsInGame) &&
        Objects.equals(this.rating, player.rating) &&
        Objects.equals(this.ratingAverage, player.ratingAverage) &&
        Objects.equals(this.pace, player.pace) &&
        Objects.equals(this.shooting, player.shooting) &&
        Objects.equals(this.passing, player.passing) &&
        Objects.equals(this.dribbling, player.dribbling) &&
        Objects.equals(this.defending, player.defending) &&
        Objects.equals(this.physicality, player.physicality) &&
        Objects.equals(this.paceAttributes, player.paceAttributes) &&
        Objects.equals(this.shootingAttributes, player.shootingAttributes) &&
        Objects.equals(this.passingAttributes, player.passingAttributes) &&
        Objects.equals(this.dribblingAttributes, player.dribblingAttributes) &&
        Objects.equals(this.defendingAttributes, player.defendingAttributes) &&
        Objects.equals(this.physicalityAttributes, player.physicalityAttributes) &&
        Objects.equals(this.goalkeeperAttributes, player.goalkeeperAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, resourceId, name, age, resourceBaseId, futBinId, futWizId, firstName, lastName, commonName, height, weight, birthDate, league, nation, club, rarity, traits, specialities, tradeable, position, skillMoves, weakFoot, foot, attackWorkRate, defenseWorkRate, totalStats, totalStatsInGame, rating, ratingAverage, pace, shooting, passing, dribbling, defending, physicality, paceAttributes, shootingAttributes, passingAttributes, dribblingAttributes, defendingAttributes, physicalityAttributes, goalkeeperAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Player {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    resourceBaseId: ").append(toIndentedString(resourceBaseId)).append("\n");
    sb.append("    futBinId: ").append(toIndentedString(futBinId)).append("\n");
    sb.append("    futWizId: ").append(toIndentedString(futWizId)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    commonName: ").append(toIndentedString(commonName)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    league: ").append(toIndentedString(league)).append("\n");
    sb.append("    nation: ").append(toIndentedString(nation)).append("\n");
    sb.append("    club: ").append(toIndentedString(club)).append("\n");
    sb.append("    rarity: ").append(toIndentedString(rarity)).append("\n");
    sb.append("    traits: ").append(toIndentedString(traits)).append("\n");
    sb.append("    specialities: ").append(toIndentedString(specialities)).append("\n");
    sb.append("    tradeable: ").append(toIndentedString(tradeable)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    skillMoves: ").append(toIndentedString(skillMoves)).append("\n");
    sb.append("    weakFoot: ").append(toIndentedString(weakFoot)).append("\n");
    sb.append("    foot: ").append(toIndentedString(foot)).append("\n");
    sb.append("    attackWorkRate: ").append(toIndentedString(attackWorkRate)).append("\n");
    sb.append("    defenseWorkRate: ").append(toIndentedString(defenseWorkRate)).append("\n");
    sb.append("    totalStats: ").append(toIndentedString(totalStats)).append("\n");
    sb.append("    totalStatsInGame: ").append(toIndentedString(totalStatsInGame)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    ratingAverage: ").append(toIndentedString(ratingAverage)).append("\n");
    sb.append("    pace: ").append(toIndentedString(pace)).append("\n");
    sb.append("    shooting: ").append(toIndentedString(shooting)).append("\n");
    sb.append("    passing: ").append(toIndentedString(passing)).append("\n");
    sb.append("    dribbling: ").append(toIndentedString(dribbling)).append("\n");
    sb.append("    defending: ").append(toIndentedString(defending)).append("\n");
    sb.append("    physicality: ").append(toIndentedString(physicality)).append("\n");
    sb.append("    paceAttributes: ").append(toIndentedString(paceAttributes)).append("\n");
    sb.append("    shootingAttributes: ").append(toIndentedString(shootingAttributes)).append("\n");
    sb.append("    passingAttributes: ").append(toIndentedString(passingAttributes)).append("\n");
    sb.append("    dribblingAttributes: ").append(toIndentedString(dribblingAttributes)).append("\n");
    sb.append("    defendingAttributes: ").append(toIndentedString(defendingAttributes)).append("\n");
    sb.append("    physicalityAttributes: ").append(toIndentedString(physicalityAttributes)).append("\n");
    sb.append("    goalkeeperAttributes: ").append(toIndentedString(goalkeeperAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

