/*
 * FutDB
 * The Fifa Ultimate Team Database API is a JSON REST API.<br> We offer a complete, easy to understand JSON REST API with a complete database of players, prices, nations, leagues, clubs, and card-types.<br> Please note that some data fields are only delivered with a premium account.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * PlayerPhysicality
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-24T14:15:34.912+02:00")
public class PlayerPhysicality {
  @SerializedName("jumping")
  private Integer jumping = null;

  @SerializedName("stamina")
  private Integer stamina = null;

  @SerializedName("strength")
  private Integer strength = null;

  @SerializedName("aggression")
  private Integer aggression = null;

  public PlayerPhysicality jumping(Integer jumping) {
    this.jumping = jumping;
    return this;
  }

   /**
   * Get jumping
   * @return jumping
  **/

  public Integer getJumping() {
    return jumping;
  }

  public void setJumping(Integer jumping) {
    this.jumping = jumping;
  }

  public PlayerPhysicality stamina(Integer stamina) {
    this.stamina = stamina;
    return this;
  }

   /**
   * Get stamina
   * @return stamina
  **/

  public Integer getStamina() {
    return stamina;
  }

  public void setStamina(Integer stamina) {
    this.stamina = stamina;
  }

  public PlayerPhysicality strength(Integer strength) {
    this.strength = strength;
    return this;
  }

   /**
   * Get strength
   * @return strength
  **/

  public Integer getStrength() {
    return strength;
  }

  public void setStrength(Integer strength) {
    this.strength = strength;
  }

  public PlayerPhysicality aggression(Integer aggression) {
    this.aggression = aggression;
    return this;
  }

   /**
   * Get aggression
   * @return aggression
  **/

  public Integer getAggression() {
    return aggression;
  }

  public void setAggression(Integer aggression) {
    this.aggression = aggression;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerPhysicality playerPhysicality = (PlayerPhysicality) o;
    return Objects.equals(this.jumping, playerPhysicality.jumping) &&
        Objects.equals(this.stamina, playerPhysicality.stamina) &&
        Objects.equals(this.strength, playerPhysicality.strength) &&
        Objects.equals(this.aggression, playerPhysicality.aggression);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jumping, stamina, strength, aggression);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerPhysicality {\n");
    
    sb.append("    jumping: ").append(toIndentedString(jumping)).append("\n");
    sb.append("    stamina: ").append(toIndentedString(stamina)).append("\n");
    sb.append("    strength: ").append(toIndentedString(strength)).append("\n");
    sb.append("    aggression: ").append(toIndentedString(aggression)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

